"""Generate the easy-to-beat sample leaderboard (SQL seed + frontend fallback).

Run:  python3 scripts/gen-leaderboard-seed.py
Writes supabase/migrations/20261009000000_seed_leaderboard.sql and src/lib/sampleLeaderboard.ts
All sample players are rated well below the 1200 starting rating, so real players
climb past them quickly.
"""
import json, random, uuid

NAMES = """
pawnstorm_pete sleepyrook knightowl42 cardshark_kim queenie_b drawtwo_dan bishopblues casual_carl
wildcard_wes reverse_rita checkmate_cat unolucy rookie_rob tea_and_tempo midnightmover blunderbuss
gambit_gus lonelyking castle_carla enpassant_ed forkfinder skewer_sam pinnedpaul zugzwangzoe
promote_pam tempo_tom hangingqueen lucky_draw_lu shuffle_sid cozyknight greenmatcher redreverser
bluebishop_bo yellowfellow eighth_rank_al hfile_holly afile_annie dealer_dee kingwalker mellowmate
pocketpawn sunday_sacs quietqueen slowclock_sue drawishdave trickytrade benchwarmer_ben endgame_elle
""".split()

rng = random.Random(20261009)
NS = uuid.UUID('6d7a1f3e-1f0b-4c5e-9a43-0c4f3b7d2a10')
players = []
for i, name in enumerate(NAMES):
    pid = str(uuid.uuid5(NS, name))
    base = rng.randint(640, 1150)
    cats = {}
    for cat, spread in (('bullet', 120), ('blitz', 0), ('rapid', 90)):
        r = max(600, min(1150, base + rng.randint(-spread, spread)))
        games = rng.randint(10, 140)
        wins = int(games * rng.uniform(0.3, 0.5))
        draws = int(games * rng.uniform(0.02, 0.1))
        losses = games - wins - draws
        cats[cat] = dict(rating=r, rd=rng.randint(60, 105), games=games, wins=wins, draws=draws, losses=losses,
                         peak=r + rng.randint(5, 90))
    players.append(dict(id=pid, username=name, cats=cats))

# ── SQL ──
sql = ["""-- ════════════════════════════════════════════════════════════════════
-- Sample leaderboard: easy-to-beat placeholder players (all below 1200).
-- Generated by scripts/gen-leaderboard-seed.py — idempotent, safe to re-run.
-- These accounts have no password and an .invalid email, so nobody can log in.
-- Remove them any time with:
--   delete from auth.users where email like '%@seed.unochess.invalid';
-- ════════════════════════════════════════════════════════════════════
"""]
vals = []
for p in players:
    meta = json.dumps({'username': p['username']}).replace("'", "''")
    vals.append(f"  ('{p['id']}', '{p['username']}@seed.unochess.invalid', '{meta}')")
sql.append("""insert into auth.users (
  instance_id, id, aud, role, email, encrypted_password, email_confirmed_at,
  raw_app_meta_data, raw_user_meta_data, created_at, updated_at,
  confirmation_token, email_change, email_change_token_new, recovery_token
)
select '00000000-0000-0000-0000-000000000000', v.id::uuid, 'authenticated', 'authenticated', v.email, '', now() - interval '60 days',
       '{"provider":"email","providers":["email"]}'::jsonb, v.meta::jsonb, now() - interval '60 days', now(),
       '', '', '', ''
from (values
""" + ",\n".join(vals) + """
) as v(id, email, meta)
on conflict (id) do nothing;
""")
sql.append("""-- Deterministic adventurer avatars + names (the sign-up trigger may have added a number suffix).
update public.profiles p
set username = split_part(u.email, '@', 1),
    avatar_url = 'https://api.dicebear.com/9.x/adventurer/svg?seed=' || replace(split_part(u.email, '@', 1), '.', '')
from auth.users u
where u.id = p.id and u.email like '%@seed.unochess.invalid'
  and not exists (select 1 from public.profiles o where o.username = split_part(u.email, '@', 1) and o.id <> p.id);
""")
rows = []
for p in players:
    for cat, c in p['cats'].items():
        rows.append(f"  ('{p['id']}', '{cat}', {c['rating']}, {c['rd']}, 0.06, {c['games']}, {c['wins']}, {c['losses']}, {c['draws']}, {c['peak']})")
sql.append("""insert into public.ratings (user_id, category, rating, rd, vol, games, wins, losses, draws, peak)
values
""" + ",\n".join(rows) + """
on conflict (user_id, category) do nothing;
""")
sql.append("""-- A short rating history per player so profile charts aren't empty.
insert into public.rating_history (user_id, category, rating, created_at)
select r.user_id, r.category,
       r.rating + (random() * 80 - 40) * (8 - g) / 8.0,
       now() - (g || ' days')::interval * 6
from public.ratings r
join auth.users u on u.id = r.user_id and u.email like '%@seed.unochess.invalid'
cross join generate_series(0, 7) as g
where not exists (select 1 from public.rating_history h where h.user_id = r.user_id and h.category = r.category);
""")
open('supabase/migrations/20261009000000_seed_leaderboard.sql', 'w').write("\n".join(sql))

# ── TS fallback ──
ts_rows = []
for cat in ('bullet', 'blitz', 'rapid'):
    ranked = sorted(players, key=lambda p: -p['cats'][cat]['rating'])
    for p in ranked:
        c = p['cats'][cat]
        ts_rows.append([cat, p['id'], p['username'], c['rating'], c['rd'], c['games'], c['wins'], c['losses'], c['draws'], c['peak']])
ts = """// Generated by scripts/gen-leaderboard-seed.py — do not edit by hand.
// Easy-to-beat sample players shown when the live leaderboard is empty or unavailable.
// The same players are seeded into Supabase by supabase/migrations/20261009000000_seed_leaderboard.sql.
import type { TimeCategory } from '@/game/rating';

export interface LeaderboardRow {
  rank: number;
  user_id: string;
  username: string;
  avatar_url: string | null;
  rating: number;
  rd: number;
  games: number;
  wins: number;
  losses: number;
  draws: number;
  peak: number;
}

type Raw = [TimeCategory, string, string, number, number, number, number, number, number, number];

// prettier-ignore
const RAW: Raw[] = """ + json.dumps(ts_rows) + """;

export function sampleLeaderboard(category: TimeCategory): LeaderboardRow[] {
  return RAW.filter((r) => r[0] === category).map((r, i) => ({
    rank: i + 1,
    user_id: r[1],
    username: r[2],
    avatar_url: `https://api.dicebear.com/9.x/adventurer/svg?seed=${r[2].replace(/\\./g, '')}`,
    rating: r[3],
    rd: r[4],
    games: r[5],
    wins: r[6],
    losses: r[7],
    draws: r[8],
    peak: r[9],
  }));
}

export const SAMPLE_IDS = new Set(RAW.map((r) => r[1]));

/** Ratings for one sample player across all categories (for their profile page). */
export function sampleProfile(username: string): { username: string; avatar_url: string; ratings: Record<TimeCategory, LeaderboardRow> } | null {
  const rows = (['bullet', 'blitz', 'rapid'] as TimeCategory[]).map((c) => sampleLeaderboard(c).find((r) => r.username.toLowerCase() === username.toLowerCase()));
  if (rows.some((r) => !r)) return null;
  const [bullet, blitz, rapid] = rows as LeaderboardRow[];
  return { username: blitz!.username, avatar_url: blitz!.avatar_url!, ratings: { bullet: bullet!, blitz: blitz!, rapid: rapid! } };
}
"""
open('src/lib/sampleLeaderboard.ts', 'w').write(ts)
print(len(players), 'players')
